<?xml version="1.0"?>
<package format="3">
  <name>commande</name>
  <version>4.0.0</version>
  <description>commande node</description>

  <maintainer email="projetlong.aip@gmail.com">Projet Long ENSEEIHT</maintainer>
  <license>GPLv3</license>
  
  <!-- Build tool -->
  <buildtool_depend>ament_cmake</buildtool_depend>
  
  <!-- Build dependencies -->
  <build_depend>rclcpp</build_depend>
  <build_depend>std_msgs</build_depend>
  <build_depend>sensor_msgs</build_depend>
  <build_depend>robots</build_depend>
  <build_depend>commande_locale</build_depend>
  <build_depend>shuttles</build_depend>
  <build_depend>image_transport</build_depend>
  <depend>opencv</depend>

  <!-- Execution dependencies -->
  <exec_depend>rclcpp</exec_depend>
  <exec_depend>std_msgs</exec_depend>
  <exec_depend>sensor_msgs</exec_depend>
  <exec_depend>robots</exec_depend>
  <exec_depend>commande_locale</exec_depend>
  <exec_depend>shuttles</exec_depend>
  <exec_depend>image_transport</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
