std_msgs/Header header

int32 id # identifiant de la navette
bool[9] cpi # capteur de position indexé, situé aux postes de travail
bool[11] cp # capteur de position convoyeur
bool[25] ps # capteur stop 
bool[13] dg # detection gauche Tableau de booléens representant les capteurs physique dans CoppeliaSim
bool[13] dd # detection droite Tableau de booléens representant les capteurs physique dans CoppeliaSim 
